servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "captain"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "Nitral-AI/Captain-Eris_Violet-V0.420-12B"
    replicaCount: 1

    requestCPU: 10
    requestMemory: "16Gi"
    requestGPU: 1

    pvcStorage: "50Gi"
    pvcAccessMode:
      - ReadWriteOnce
    pvcMatchLabels:
      model: "Captain-Eris_Violet-V0.420-12B-pv"

    vllmConfig:
      maxModelLen: 10000

